[workspace]
members = ["oh-canonical", "oh-canonical-wasm", "oh-canonical-napi", "oh-canonical-raw-wasm", "oh-archive", "oh-archive-wasm", "oh-archive-napi", "oh-archive-strict-wasm", "oh-sqlite", "oh-sqlite-napi", "oh-datalog", "oh-datalog-wasm"]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["Hraness"]
edition = "2024"
license = "MIT"
repository = "https://github.com/hraness/oh"
rust-version = "1.85"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
hex = "0.4"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde-wasm-bindgen = "0.6"

[workspace.metadata.release]
publish = false

[profile.release]
codegen-units = 1
lto = "thin"
strip = true
panic = "abort"
